config/routes.rb
Zard::Application.routes.draw do
  resources :songs
  resources :images
  resources :movies

  resource :user_session
  resources :users
  resource :account,:controller => "users"
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "zard/songs" => "sister#songs"
  match "zard/images" => "sister#images"
  match "zard/movies" => "sister#movies"
  match "categories" => "songs#category_index"
  match "category" => "songs#add_category"
  match "new/category" => "songs#create_category"
  match "category/:id/edit" => "songs#edit_category",:as => :edit
  match "category/:id/update" => "songs#update_category",:as => :update
  match "category/:id/destroy" => "songs#destroy_category",:as => :delete
  match "song/:id/love" => "sister#song_love",:as => :love
  match "song/:id/listen" => "sister#listen_song",:as => :listen#display song.lyric page

  

  root :to => "sister#index"

end

app/controllers/sister_controller.rb
class SisterController < ApplicationController
  #caches_page :index
  def index
    @title = "Beautiful Heart"
    @songs = Song.all
  end

  def songs
    @title = "Beautiful Sounds"
      @categories = Category.paginate :page => params[:page],:per_page => 4
    
    respond_to do |format|
      format.js
      format.html 
    end
    
  end

  def images
    @title = "Beautiful Memory"
    @images = Image.paginate :page => params[:page], :per_page => 16
    respond_to do |format|
      format.html # index.html.haml
      format.xml  { render :xml => @images }
    end
  end

  def movies
    @title = "Beautiful Moment"
    @movies = Movie.all
  end
  
  def song_love
    @song = Song.find(params[:id])
    @love = @song.love+1
    @song.update_attribute(:love,@love)
    respond_to do |format|
      format.js
    end
  end
  
  def listen_song
    @song = Song.find(params[:id])
    render :partial => "lyric"
  end

end

app/helpers/sister_helper.rb
module SisterHelper
end

app/views/sister/_images.html.haml
.paginate.clear.round
	= will_paginate @images
- for image in @images
	.image
		= link_to image_tag(image.url,:width=>"180",:height=>"150",:class =>"link"),image.url,:rel=>"colorbox"
.paginate.clear.round
	= will_paginate @images
%script
	QueryLoader.init();

app/views/sister/_lyric.html.haml
%h3
	= @song.title
%p
	=raw @song.lyric

app/views/sister/_sidebar.html.haml
#friend-link
	%ul.side
		= link_to "http://www.wezard.net/",:class=>"tip",:target => '_blank',:title=>"日本官网",:alt=>"日本官网" do
			%li ZARD Official
		= link_to "http://ameblo.jp/honmei-ani/",:class=>"tip",:target => '_blank',:title=>"一个有意思的博客",:alt=>"一个有意思的博客" do
			%li Jap Blog
		= link_to "http://www.kokia.com/",:class => "tip",:target => '_blank',:title=>"我很喜欢的音乐家",:alt=>"我很喜欢的音乐家" do
			%li Kokia Official
		= link_to "http://alan-web.jp/index.html",:class=>"tip",:target => '_blank',:title=>"支持alan",:alt=>"支持alan" do
			%li Alan Official
		= link_to "http://beingmusic.jp/bbs/forumdisplay.php?fid=180",:target => '_blank',:class =>"tip",:title =>"日本音乐料理店ZARD bbs",:alt=>"日本音乐料理店ZARD bbs" do
			%li 日本音乐料理店
		= link_to "http://www.xiami.com/artist/7107",:target => '_blank' do
			%li ZARD虾米
		= link_to "http://tieba.baidu.com/f?fr=bk&kw=ZARD",:target => '_blank' do
			%li ZARD百度贴吧
		= link_to "http://www.verycd.com/topics/2749516/",:class=>"tip",:target => '_blank',:title=>"VeryCD上的资源",:alt=>"VeryCD上的资源" do
			%li ZARD无损全专辑
#my-link
	%ul.side
		= link_to "http://heartme.heroku.com",:class=>"tip",:title=>"我的博客",:alt=>"我的博客" do
			%li My Blog
		= link_to "http://rainbowmark.heroku.com",:class=>"tip",:title=>"我的在线书签收藏",:alt=>"我的在线书签收藏" do
			%li Rainbowmark
		= link_to "http://booksoul.heroku.com",:class => "tip",:title => "书魂主站",:alt => "书魂主站" do
			%li BookSoul
		= link_to "http://anothercountry.heroku.com",:class => "tip",:title => "我最喜欢的小说",:alt => "我最喜欢的小说" do
			%li 远方有个女儿国
		= link_to "http://talk1988.heroku.com",:class => "tip",:title => "我想和这个世界谈谈",:alt => "我想和这个世界谈谈" do
			%li 1988--韩寒
#board.round
	%ul.side
		= link_to "http://booksoul.heroku.com/chat",:class => "tip",:title => "留言纷飞",:alt =>"留言纷飞" do
			%li 给我留言吧
<!-- GoStats JavaScript Based Code -->
<script type="text/javascript" src="http://gostats.cn/js/counter.js"></script>
<script type="text/javascript">_gos='monster.gostats.cn';_goa=441513;
_got=7;_goi=3;_goz=0;_god='hits';_gol='qq空间流量统计';_GoStatsRun();</script>
<noscript><a target="_blank" title="qq空间流量统计" 
href="http://gostats.cn"><img alt="qq空间流量统计" 
src="http://monster.gostats.cn/bin/count/a_441513/t_7/i_3/z_0/show_hits/counter.png" 
style="border-width:0" /></a></noscript>
<!-- End GoStats JavaScript Based Code -->
#adside
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-9765425002757717";
	/* zard1 */
	google_ad_slot = "3686222745";
	google_ad_width = 200;
	google_ad_height = 200;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	

app/views/sister/_songs.html.haml
.paginate.clear.round
	= will_paginate @categories
#temp
	- for category in @categories
		.category{:onclick =>"$('#category_#{category.id}').slideToggle('slow');"}
			.category-image
				= image_tag(category.image,:width=>"200",:height=>"180")
			.category-info
				%h3
				= category.title
				%p
				发行日期：
				= category.date.strftime('%Y-%m')
				- @songs = Song.where(["category_id = ?",category.id]).order("love DESC")
				%br
				= @songs.size
				首已收录
		.toggle{:id => dom_id(category)}
			%ul.song
				- for song in @songs
					%li.round{:class => cycle('c3','c4') }
						= song.title 
						= link_to "欣赏音乐",listen_url(song),:class =>"listen round"
						= link_to image_tag('/images/love.png'),love_url(song),:remote=>true,:class=>dom_id(song)
						.love{:id => dom_id(song)}
							= song.love
							fans
.paginate.clear.round
	= will_paginate @categories

app/views/sister/images.html.haml
#images
	= render :partial => 'images' 
	

	

app/views/sister/images.js.erb
$("#images").html("<%= escape_javascript(render('images'))%>");

app/views/sister/index.html.haml
#sister-info
	#left-info
		%h3 坂井泉水 
		%ul
			%li さかいいずみ(Izumi Sakai)
			%li ZARD的主唱 作词 作曲 监制
			%li 原名: 蒲池幸子 
			%li	生日: 1967年2月6日 
			%li 血型: A型 
			%li	星座: 水瓶 
			%li	身高: 165 CM 
			%li	出生地: 神奈川县秦野市
		%p
		<iframe src="http://www.google.com/talk/service/badge/Show?tk=z01q6amlq4ddm5uk744a9k7ueg0aueuuvs7gd38k77915olc3falpj6ceecer43q8krjjj5ak2rj7o6k5fjksvhc8rtdfh5quuvnc9m1mhpc84hsd1k5krtrigp17aqltf9ev8es99g1d9aimjpcjdr7phngbbie64an5dhem&amp;w=200&amp;h=60" frameborder="0" allowtransparency="true" width="200" height="60"></iframe>
		%br
		虽然知道泉水姐姐的存在的时候，她已经去了遥远的地方，但她的歌声留了下来，我想为泉水姐做点什么，于是做了这个小站,同时也作为我的音乐博客。
		= mail_to "kkxlkkxllb@gmail.com"
		%p
		= audio_tag("http://www.wezard.net/bgm/o/3.mp3", :autoplay => true)
	#coin-slider
		= image_tag("http://lh6.ggpht.com/_tQAlkqizbcs/SCG3ERh3jgI/AAAAAAAAASk/RNEC895euaU/1137136910.jpg")
		= image_tag("http://lh3.ggpht.com/_zqzDFhmRLSc/Rl1iN2AO2nI/AAAAAAAADRw/4kWxxN465Qo/s640/zard25.jpg")
		= image_tag("http://lh5.ggpht.com/_j6cxaUcuPkw/SXcVNM51WBI/AAAAAAAADjk/hvhntQOkC0Q/1951570.jpg")
		= image_tag("http://lh4.ggpht.com/_aLKf02xsm6Y/SchDMFTvKcI/AAAAAAAAAS8/QIizHbgcSrs/s640/1053241_070709zard06.jpg")
		= image_tag("http://lh6.ggpht.com/_X3Y7UibB-hw/TK3cgw_56cI/AAAAAAAAAZQ/6lqvD4LcMDs/s640/7.jpg")
		= image_tag("http://lh4.ggpht.com/_aLKf02xsm6Y/SchDM93wlRI/AAAAAAAAATE/cfPqyZiJpME/s640/1053241_070709zard07.jpg")
		= image_tag("http://lh3.ggpht.com/_tQAlkqizbcs/SHRb-h1MglI/AAAAAAAAAes/t0dWk7xY9KM/s640/image_1042003.jpg")
		= image_tag("http://lh6.ggpht.com/_UdLb97T5vng/Rn4SvvLx3aI/AAAAAAAAAAw/bkMtrPHv6TY/s640/zard.jpg")
#foot
	= "已有#{@songs.count}首歌曲收录"
	= link_to "立即欣赏好音乐",zard_songs_path
#applet
	#visiter
		<script type="text/javascript" src="http://jc.revolvermaps.com/r.js"></script><script type="text/javascript">rm_f1st('0','220','true','false','ddfbb4','25f8nwuzfzb','true','ff8a00');</script><noscript><applet codebase="http://rc.revolvermaps.com/j" code="core.RE" width="220" height="220" archive="g.jar"><param name="cabbase" value="g.cab" /><param name="r" value="true" /><param name="n" value="false" /><param name="i" value="25f8nwuzfzb" /><param name="m" value="0" /><param name="s" value="220" /><param name="c" value="ff8a00" /><param name="v" value="true" /><param name="b" value="ddfbb4" /><param name="rfc" value="true" /></applet></noscript>
	#ads
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-9765425002757717";
		/* zard2 */
		google_ad_slot = "1553741629";
		google_ad_width = 468;
		google_ad_height = 60;
		//-->
		</script>
		<script type="text/javascript"
		src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>

app/views/sister/movies.html.haml
%h2 影像资源分享
- for movie in @movies
	.movie
		.movie-image
			= image_tag(movie.image,:width=>"200",:height=>"180")
		.movie-info
			= link_to movie.title,movie.url
			%p
			=raw movie.info

app/views/sister/song_love.js.erb
$(".song_<%=@song.id%>").hide();
$("#song_<%=@song.id%>").replaceWith("<div id='love_<%=@song.id%>'class='love'><%= @song.love %>fans</div>");
$("#love_<%=@song.id%>").effect("pulsate");

app/views/sister/songs.html.haml
#songs
	= render :partial => 'songs'
#song-end.round
	以上内容选自ZARD Official，专辑全收录
:javascript
	$('.pagination a').live('click',function(){$(".pagination").html("Page is loading...");$.get(this.href);history.pushState(null, "", this.href);return false;});
	$(window).bind("popstate", function () {  
	  $.getScript(location.href);  
	});

			
		

app/views/sister/songs.js.erb
setTimeout(function(){ $('.listen').nyroModal({
	bgColor:'#ecd8fb'
});
$('.tip').poshytip({
	className: 'tip-twitter',
		bgImageFrameSize: 9,
		offsetX: -20,
		offsetY: 20		
});}, 1000);
$("#songs").html("<%= escape_javascript(render('songs'))%>");