config/routes.rb
Zard::Application.routes.draw do
  resources :songs
  resources :images
  resources :movies

  resource :user_session
  resources :users
  resource :account,:controller => "users"
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "zard/songs" => "sister#songs"
  match "zard/images" => "sister#images"
  match "zard/movies" => "sister#movies"
  match "categories" => "songs#category_index"
  match "category" => "songs#add_category"
  match "new/category" => "songs#create_category"
  match "category/:id/edit" => "songs#edit_category",:as => :edit
  match "category/:id/update" => "songs#update_category",:as => :update
  match "category/:id/destroy" => "songs#destroy_category",:as => :delete
  match "song/:id/love" => "sister#song_love",:as => :love
  match "song/:id/listen" => "sister#listen_song",:as => :listen#display song.lyric page

  

  root :to => "sister#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/controllers/users_controller.rb
class UsersController < ApplicationController   
    def new
      @title = "Register"
      @user = User.new
    end

    def create
      @user = User.new(params[:user])
      if @user.save
        
        redirect_back_or_default root_path
      else
        redirect_to register_path
      end
    end

    
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
%p
	= form.label :login
	= form.text_field :login,:class => "field"
%p
	= form.label :email
	= form.text_field :email,:class => "field"
%p
	= form.label :password, form.object.new_record? ? nil : "Change password"
	= form.password_field :password,:class => "field"
%p
	= form.label :password_confirmation
	= form.password_field :password_confirmation,:class => "field"
%p
	= form.submit "Submit"

app/views/users/new.html.haml
.form.round
	- form_for @user, :url => account_path do |f|
		= render :partial => "form", :object => f