config/routes.rb
Zard::Application.routes.draw do
  resources :songs
  resources :images
  resources :movies

  resource :user_session
  resources :users
  resource :account,:controller => "users"
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "zard/songs" => "sister#songs"
  match "zard/images" => "sister#images"
  match "zard/movies" => "sister#movies"
  match "categories" => "songs#category_index"
  match "category" => "songs#add_category"
  match "new/category" => "songs#create_category"
  match "category/:id/edit" => "songs#edit_category",:as => :edit
  match "category/:id/update" => "songs#update_category",:as => :update
  match "category/:id/destroy" => "songs#destroy_category",:as => :delete
  match "song/:id/love" => "sister#song_love",:as => :love
  match "song/:id/listen" => "sister#listen_song",:as => :listen#display song.lyric page

  

  root :to => "sister#index"

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :category
  validates :title,:presence => true,:uniqueness => {:scope => :category_id }
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :require_user
  # GET /songs
  # GET /songs.xml
  def index
    @songs = Song.paginate :page => params[:page],:per_page => 30,:order => 'category_id ASC'
    @title = "Manage Songs"
    respond_to do |format|
      format.js
      format.html # index.html.haml
      format.xml  { render :xml => @songs }
    end
  end

  # GET /songs/new
  # GET /songs/new.xml
  def new
    @song = Song.new
    @title = "New Song"
    respond_to do |format|
      format.html # new.html.haml
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
    @title = "Edit Song"
  end

  # POST /songs
  # POST /songs.xml
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        #expire_fragment(:controller => 'sister',:action => 'songs')
        format.html { redirect_to songs_path }
        format.xml  { render :xml => @song, :status => :created, :location => @song }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.xml
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        #expire_fragment(:controller => 'sister',:action => 'songs')
        format.html { redirect_to songs_path }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.xml
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    #expire_fragment(:controller => 'sister',:action => 'songs')
    respond_to do |format|
      format.html { redirect_to(songs_path) }
      format.xml  { head :ok }
    end
  end
  
  def category_index
    @title = "All categories"
    @categories = Category.all
  end
#view add_category.html.haml
  def add_category
    @title = "Add Category"
    @category = Category.new
  end
# Post 
  def create_category
    @category = Category.new(params[:category])
    if @category.save
      #expire_fragment(:controller => 'sister',:action => 'songs')
      redirect_to categories_path
    else
      redirect_to category_path
    end
  end
  
  def edit_category
    @title = "Edit Category"
    @category = Category.find(params[:id])
  end
  
  def update_category
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit_category" }
      end
    end
  end
  
  def destroy_category
    @category = Category.find(params[:id])
    @category.destroy
    #expire_fragment(:controller => 'sister',:action => 'songs')
    redirect_to zard_songs_path  
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
= form_for @song do |f|
	%p
	= f.label :title
	= f.text_field :title
	= f.label :url
	= f.text_field :url
	%p
	= f.label :category_id
	= f.select :category_id,Category.all.collect{|s| [s.title,s.id]}
	%p
	= f.label :lyric
	= f.text_area :lyric
	%p
	= f.submit 'Save'

app/views/songs/_sidebar.html.haml
%ul.side
	%li= link_to_unless_current "New Category",category_path
	%li= link_to_unless_current "New Songs",new_song_path
	%li= link_to_unless_current "Edit categories",categories_path
#clock
	<embed src="/swf/blogparts.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="140" height="290" wmode="transparent">

app/views/songs/_songs.html.haml
.paginate.round= will_paginate @songs
%table
	%tr
		%th Id
		%th Title
		%th Category
		%th Love

	- @songs.each do |song|
		%tr{:class => cycle('c1','c2') }
			%td= song.id
			%td= song.title
			%td= Category.find(song.category_id).title
			%td= song.love
			%td= link_to 'Edit', edit_song_path(song)
			%td= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete
.paginate.round= will_paginate @songs

app/views/songs/add_category.html.haml
.form.round
	- form_for @category,:url => new_category_path do |f|
		%p
		=f.label :title
		=f.text_field :title,:class => 'field'
		%p
		=f.label :iamge
		=f.text_field :image,:class => 'field'
		%p
		=f.label :date
		=f.date_select :date,:start_year => 1990,:order => [:year,:month]
		%p
		=f.submit

app/views/songs/category_index.html.haml
%table
	%tr
		%th Id
		%th Title

	- @categories.each do |category|
		%tr{:class => cycle('c1','c2') }
			%td= category.id
			%td= category.title
			%td= link_to 'Edit', edit_path(category)
			

app/views/songs/edit.html.haml
= render 'form'

= link_to 'Back', songs_path

app/views/songs/edit_category.html.haml
.form.round
	- form_for @category,:url => update_path do |f|
		%p
		=f.label :title
		=f.text_field :title,:class => 'field'
		%p
		=f.label :iamge
		=f.text_field :image,:class => 'field'
		%p
		=f.label :date
		=f.date_select :date,:start_year => 1990,:order => [:year,:month]
		%p
		=f.submit

app/views/songs/index.html.haml
#songs
	= render :partial => 'songs' 

:javascript
	$('.pagination a').live('click',function(){$(".pagination").html("Page is loading...");$.get(this.href, null, null, "script");return false;});

app/views/songs/index.js.erb
$("#songs").html("<%= escape_javascript(render('songs'))%>");

app/views/songs/new.html.haml
= render 'form'

= link_to 'Back', songs_path