config/routes.rb
Zard::Application.routes.draw do
  resources :songs
  resources :images
  resources :movies

  resource :user_session
  resources :users
  resource :account,:controller => "users"
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "zard/songs" => "sister#songs"
  match "zard/images" => "sister#images"
  match "zard/movies" => "sister#movies"
  match "categories" => "songs#category_index"
  match "category" => "songs#add_category"
  match "new/category" => "songs#create_category"
  match "category/:id/edit" => "songs#edit_category",:as => :edit
  match "category/:id/update" => "songs#update_category",:as => :update
  match "category/:id/destroy" => "songs#destroy_category",:as => :delete
  match "song/:id/love" => "sister#song_love",:as => :love
  match "song/:id/listen" => "sister#listen_song",:as => :listen#display song.lyric page

  

  root :to => "sister#index"

end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= @title
		%meta{'http-equiv' => "content-type", :content => "text/html; charset=UTF-8"}
		%meta{'name' => "description", :content => "zard music station"}
		%meta{'name' => "keywords", :content => "ZARD,坂井泉水,Izumi Sakai"}
		= stylesheet_link_tag :all
		
		= javascript_include_tag :defaults,'jquery.cleditor.min.js','coin-slider.min.js','jquery.poshytip.min.js','jquery.nyroModal-1.6.2.min.js','queryLoader.js','jquery.colorbox-min.js','jquery-ui'
		= csrf_meta_tag
	%body
		#container
			#head.round.shadow
				#left
					%h1 
						= @title
					#navigation.round
						%ul.nav
							%li= link_to_unless_current "Home",root_path,:class => "tip",:title=>"ZARD首页",:alt =>"ZARD首页"
							%li= link_to_unless_current "Songs",zard_songs_path,:class =>"tip",:title=>"专辑分享",:alt=>"专辑分享"
							%li= link_to_unless_current "Images",zard_images_path,:class=>"tip",:title=>"姐姐的图像",:alt=>"姐姐的图像"
							%li= link_to_unless_current "Movies",zard_movies_path,:class=>"tip",:title=>"影像资源分享",:alt=>"影像资源分享"
							- if current_user
								%li= link_to_unless_current "MSong",songs_path
								%li= link_to_unless_current "NewImage",new_image_path
								%li= link_to_unless_current "MMovie",movies_path
								%li= link_to "Logout",logout_path		
				#right
					= image_tag("zard-1.jpg")
			#main.round
				= yield
			#sidebar.round
				= render :partial => 'sidebar'
			<!-- JiaThis Button BEGIN -->
			<script type="text/javascript" src="http://v2.jiathis.com/code_mini/jiathis_r.js?move=0&amp;btn=r1.gif" charset="utf-8"></script>
			<!-- JiaThis Button END -->	